---
- hosts: all
  become: true
  remote_user: ec2-user
  tasks:
     - name: install a package
       yum:
         name: docker
         state: present
     - name: start service
       service:
         name: docker
         state: started
     - command: docker info
       register: hello
     - debug:
          var: hello
       
